#!/bin/bash

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --auth-server-whitelist='*knewton.net,*knewton.com' --auth-negotiate-delegate-whitelist='*knewton.net,*knewton.com' --auth-schemes='basic,digest,negotiate' "$@"
